"""Public inventory domain facade used by the CLI and future app layer."""

from .access import (
    actor_can_read_any_inventory,
    actor_can_read_inventory,
    actor_can_manage_inventory_share,
    actor_can_write_inventory,
    actor_inventory_role,
    actor_inventory_role_with_connection,
    can_manage_inventory_share,
    can_read_inventory,
    can_write_inventory,
    grant_inventory_membership,
    grant_inventory_membership_with_connection,
    is_global_admin,
    list_inventory_memberships,
    normalize_inventory_membership_role,
    remove_inventory_membership,
    revoke_inventory_membership,
    set_inventory_membership_role,
    update_inventory_membership_role,
)
from .audit import list_inventory_audit_events
from .analysis import (
    build_duplicate_groups_from_owned_rows,
    export_inventory_csv,
    inventory_health,
    inventory_report,
    list_price_gaps,
    reconcile_prices,
    render_inventory_csv_export,
    valuation,
    valuation_filtered,
)
from .catalog import (
    list_card_printings_for_oracle,
    resolve_card_row,
    search_card_names,
    search_cards,
    summarize_card_printings_for_oracle,
)
from .csv_import import import_csv, import_csv_stream
from .decklist_import import import_decklist_text
from .deck_url_import import import_deck_url
from .inventories import create_inventory, ensure_default_inventory, list_inventories, list_visible_inventories
from .inventories import summarize_actor_access
from .owned_items import (
    OWNED_INVENTORY_PAGE_SORT_DIRECTIONS,
    OWNED_INVENTORY_PAGE_SORT_KEYS,
    list_owned,
    list_owned_filtered,
    list_owned_filtered_page,
)
from .mutations import (
    add_card,
    add_card_with_connection,
    bulk_mutate_inventory_items,
    merge_rows,
    remove_card,
    set_acquisition,
    set_condition,
    set_finish,
    set_finish_with_connection,
    set_location,
    set_notes,
    set_printing,
    set_quantity,
    set_tags,
    split_row,
)
from .sharing import (
    create_inventory_share_link,
    get_inventory_share_link_status,
    get_public_inventory_share,
    revoke_inventory_share_link,
    rotate_inventory_share_link,
)
from .transfer import duplicate_inventory, transfer_inventory_items

__all__ = [
    "OWNED_INVENTORY_PAGE_SORT_DIRECTIONS",
    "OWNED_INVENTORY_PAGE_SORT_KEYS",
    "actor_can_manage_inventory_share",
    "actor_can_read_any_inventory",
    "actor_can_read_inventory",
    "actor_can_write_inventory",
    "actor_inventory_role",
    "actor_inventory_role_with_connection",
    "add_card",
    "add_card_with_connection",
    "build_duplicate_groups_from_owned_rows",
    "bulk_mutate_inventory_items",
    "can_manage_inventory_share",
    "can_read_inventory",
    "can_write_inventory",
    "create_inventory",
    "create_inventory_share_link",
    "duplicate_inventory",
    "ensure_default_inventory",
    "export_inventory_csv",
    "get_inventory_share_link_status",
    "get_public_inventory_share",
    "grant_inventory_membership",
    "grant_inventory_membership_with_connection",
    "import_csv",
    "import_csv_stream",
    "import_deck_url",
    "import_decklist_text",
    "inventory_health",
    "inventory_report",
    "is_global_admin",
    "list_card_printings_for_oracle",
    "list_inventory_audit_events",
    "list_inventory_memberships",
    "list_inventories",
    "list_owned",
    "list_owned_filtered",
    "list_owned_filtered_page",
    "list_price_gaps",
    "list_visible_inventories",
    "merge_rows",
    "normalize_inventory_membership_role",
    "reconcile_prices",
    "remove_card",
    "render_inventory_csv_export",
    "resolve_card_row",
    "revoke_inventory_membership",
    "revoke_inventory_share_link",
    "rotate_inventory_share_link",
    "search_card_names",
    "search_cards",
    "set_acquisition",
    "set_condition",
    "set_finish",
    "set_finish_with_connection",
    "set_inventory_membership_role",
    "set_location",
    "set_notes",
    "set_printing",
    "set_quantity",
    "set_tags",
    "split_row",
    "summarize_actor_access",
    "summarize_card_printings_for_oracle",
    "transfer_inventory_items",
    "update_inventory_membership_role",
    "valuation",
    "valuation_filtered",
]
