-- Add inventory-level default metadata columns when inventories exists.
-- The migrator prepares these columns directly so this migration remains
-- compatible with legacy/dev databases that already have the columns but do
-- not yet have schema_migrations tracking recorded.
