"""Public CLI module shim for personal inventory commands."""

from .cli.inventory import build_parser, main
from .db.connection import DEFAULT_DB_PATH, connect
from .db.schema import initialize_database
from .db.snapshots import create_database_snapshot
from .inventory import service as _inventory_service
from .inventory.csv_import import import_csv
from .inventory.normalize import (
    DEFAULT_HEALTH_STALE_DAYS,
    DEFAULT_PROVIDER,
    HEALTH_PREVIEW_LIMIT,
    format_finishes,
    truncate,
)
from .inventory.service import (
    OWNED_INVENTORY_PAGE_SORT_DIRECTIONS,
    OWNED_INVENTORY_PAGE_SORT_KEYS,
    actor_can_manage_inventory_share,
    actor_can_read_any_inventory,
    actor_can_read_inventory,
    actor_can_write_inventory,
    actor_inventory_role,
    actor_inventory_role_with_connection,
    add_card,
    add_card_with_connection,
    build_duplicate_groups_from_owned_rows,
    bulk_mutate_inventory_items,
    can_manage_inventory_share,
    can_read_inventory,
    can_write_inventory,
    create_inventory,
    create_inventory_share_link,
    duplicate_inventory,
    ensure_default_inventory,
    export_inventory_csv,
    get_inventory_share_link_status,
    get_public_inventory_share,
    grant_inventory_membership,
    grant_inventory_membership_with_connection,
    import_csv_stream,
    import_deck_url,
    import_decklist_text,
    inventory_health,
    inventory_report,
    is_global_admin,
    list_card_printings_for_oracle,
    list_inventory_audit_events,
    list_inventory_memberships,
    list_inventories,
    list_owned,
    list_owned_filtered,
    list_owned_filtered_page,
    list_price_gaps,
    list_visible_inventories,
    merge_rows,
    normalize_inventory_membership_role,
    reconcile_prices,
    remove_card,
    render_inventory_csv_export,
    resolve_card_row,
    revoke_inventory_membership,
    revoke_inventory_share_link,
    rotate_inventory_share_link,
    search_card_names,
    search_cards,
    set_acquisition,
    set_condition,
    set_finish,
    set_finish_with_connection,
    set_inventory_membership_role,
    set_location,
    set_notes,
    set_printing,
    set_quantity,
    set_tags,
    split_row,
    summarize_actor_access,
    summarize_card_printings_for_oracle,
    transfer_inventory_items,
    update_inventory_membership_role,
    valuation,
    valuation_filtered,
)

__all__ = [
    "DEFAULT_DB_PATH",
    "DEFAULT_HEALTH_STALE_DAYS",
    "DEFAULT_PROVIDER",
    "HEALTH_PREVIEW_LIMIT",
    "build_parser",
    "connect",
    "create_database_snapshot",
    "format_finishes",
    "import_csv",
    "initialize_database",
    "main",
    "truncate",
    *_inventory_service.__all__,
]


if __name__ == "__main__":
    main()
